# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: Ubuntu 16.04

variables:
  buildConfiguration: Release

Jobs: 

  - Job: Build
    steps:
    - script: dotnet build --configuration $(buildConfiguration)

  - Job: Test
    steps: 
    - script: dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx
    - task: PublishTestResults@2
    inputs:
     testRunner: VSTest
     testResultsFiles: '**/*.trx'

  - Job: Publish
    steps:
    - script: dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
    - task: PublishBuildArtifacts@1