# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts


jobs: 

  - job: Build

    pool:
     vmImage: Ubuntu 16.04
    variables:
     buildConfiguration: Release

    steps:
    - script: dotnet build --configuration $(buildConfiguration)

  - job: Test

    pool:
     vmImage: Ubuntu 16.04
    variables:
     buildConfiguration: Release

    steps: 
    - script: dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx
    - task: PublishTestResults@2
      inputs:
       testRunner: VSTest
       testResultsFiles: '**/*.trx'

  - job: Publish

    pool:
     vmImage: Ubuntu 16.04
    variables:
     buildConfiguration: Release

    steps:
    - script: dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
    - task: PublishBuildArtifacts@1